apiVersion: http.crossplane.io/v1alpha2
kind: Request

metadata:
  name: github-create-ec2

spec:
  forProvider:
    headers:
      Accept:
        - application/vnd.github+json
      Authorization:
        - "Bearer {{ github-actions-token:crossplane-system:token }}"
      X-GitHub-Api-Version:
        - "2022-11-28"
      Content-Type:
        - "application/json"

    payload:
      baseUrl: https://api.github.com/repos/satishnaga1/crossplane-gitops-lab/actions/workflows/create-ec2.yml/dispatches
      body: |
        {
          "ref": "main",
          "inputs": {
            "environment": "dev",
            "region": "ap-south-1",
            "instance_type": "t2.micro",
            "instance_name": "crossplane-ec2"
          }
        }

    mappings:
      - action: CREATE
        method: POST
        url: .payload.baseUrl
        body: .payload.body
