apiVersion: platform.example.com/v1alpha1
kind: EC2Request

metadata:
  name: dev-ec2

spec:
  parameters:

    environment: dev

    region: ap-south-1

    instanceType: t3.micro

    amiId: ami-xxxxxxxx

    instanceName: dev-web
