apiVersion: http.crossplane.io/v1alpha1
kind: DisposableRequest
metadata:
  name: trigger-ec2-github-action
spec:
  providerConfigRef:
    name: github-http

  deletionPolicy: Orphan

  forProvider:
    method: POST

    url: https://api.github.com/repos/satishnaga1/ec2-github-action/actions/workflows/create-ec2.yml/dispatches

    headers:
      Accept:
        - application/vnd.github+json
      Authorization:
        - "Bearer {{ github-actions-token:crossplane-system:token }}"
      X-GitHub-Api-Version:
        - "2022-11-28"
      Content-Type:
        - application/json

    body: |
      {
        "ref": "main",
        "inputs": {
          "environment": "dev",
          "region": "us-east-1",
          "instance_type": "t2.micro",
          "instance_name": "crossplane-gitops-ec2"
        }
      }
